#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 一 二 三 四 五 六 七 八 九 十
# bspc monitor -d I II III IV V VI VII VIII IX X
# bspc monitor -d Ⅰ Ⅱ Ⅲ Ⅳ Ⅴ Ⅵ Ⅶ Ⅷ Ⅸ Ⅹ
# bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          20

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      true

# color
bspc config normal_border_color \#00BBFF
bspc config focused_border_color \#D7005F
bspc config active_border_color \#D7005F

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# rule
bspc rule -a firefox desktop='^2'
bspc rule -a feh state=floating
bspc rule -a mpv state=floating
bspc rule -a obs state=floating
bspc rule -a qv2ray state=floating
bspc rule -a qBittorrent state=floating desktop='^7'
bspc rule -a Pcmanfm state=floating
bspc rule -a TelegramDesktop state=floating
bspc rule -a VirtualBox Manager state=floating
bspc rule -a Zathura state=tiled
