#!/bin/sh

export INPUT_METHOD=fictx5
export GTK_IM_MODULE=fcitx5
export QT_IM_MODULE=fcitx5
export XMODIFIERS="@im=fcitx5"

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

xset r rate 220 45
xset s 480 480
# xmodmap ~/.Xmodmap
/usr/bin/start-pulseaudio-x11 &

exec xss-lock -- i3lock -n -B picom --indicator -k --timecolor="D7005F" --datecolor="D7005F" --ringcolor="1a1a1a" --keyhlcolor="D7005f" &
exec xautolock -time 30 -locker "systemctl suspend" &
exec fcitx5 &
exec redshift &
exec picom &
exec keynav &

exec ~/.fehbg &
exec alacritty &
exec bspwm

# abandon
# exec aria2c --conf-path=<path to aria2.conf> &
# exec i3 -V >> ~/.config/i3/log/i3log-$(date +'%F-%k-%M-%S') 2>&1
# exec ~/.startdwmstatus &
# exec ~/.startdwm
