setopt PROMPT_SUBST
unsetopt correct
setopt clobber

source ~/.zpreztorc
source ~/.lgfs_prompt.sh
source ~/.alias.sh
source ~/.utils_env.sh

# fortune -a | fmt -80 -s | $(shuf -n 1 -e cowsay cowthink) -$(shuf -n 1 -e b d g p s t w y) -f $(shuf -n 1 -e $(cowsay -l | tail -n +2)) -n | lolcat
printf "<< $(date)\n$(pfetch)" | lolcat
