setopt PROMPT_SUBST
unsetopt correct
setopt clobber

source ~/.zpreztorc
source ~/.fish.prompt.sh
source ~/.lgfs.prompt.sh
source ~/.alias.sh
source ~/.langenv
export PF_INFO="ascii title os kernel uptime pkgs wm memory"
# fortune -a | fmt -80 -s | $(shuf -n 1 -e cowsay cowthink) -$(shuf -n 1 -e b d g p s t w y) -f $(shuf -n 1 -e $(cowsay -l | tail -n +2)) -n | lolcat
printf "<< $(date)\n$(pfetch)" | lolcat
